Repository IamMrandrew/aimimi, pull requests merged in 2021-04, with the labels that each got.

#49 refactor: context provider for user
  client/src/App.jsx
  client/src/components/Nav.jsx
  client/src/contexts/AuthContext.jsx
  client/src/index.jsx
  client/src/views/Login.jsx
  server/api/middleware/auth.js
Labels: refactor

#52 fix: merge conflict
  server/index.js
Labels: fix

#53 Feat/leaderboard api
  server/api/controllers/goal.js
  server/api/models/goal.js
  server/api/models/user.js
  server/api/routes/goal.js
Labels: feature, fix

#54 fix: fix bracket error
  server/api/controllers/goal.js
Labels: fix

#55 feat: check in goal frontend
  server/api/controllers/goal.js
  server/api/routes/goal.js
Labels: feature, fix

#56 feat: check in goal frontend
  client/src/App.jsx
  client/src/components/CheckInModal.jsx
  client/src/components/Goal.jsx
  client/src/components/Overlay.jsx
  client/src/views/Today.jsx
  server/api/controllers/goal.js
  server/api/controllers/user.js
Labels: feature, fix, style

#58 fix: error
  client/src/App.jsx
  server/api/routes/goal.js
Labels: fix

#59 style: sidebar hover
  client/src/App.jsx
  client/src/components/GlobalStyle.jsx
  client/src/components/NavItem.jsx
  client/src/components/Sidebar.jsx
Labels: feature, style

#60 fix: import typo
  client/src/components/Details.jsx
Labels: fix

#61 Feat/leaderboard api
  server/api/controllers/goal.js
  server/api/controllers/user.js
  server/api/models/goal.js
  server/api/models/user.js
  server/api/routes/goal.js
  server/index.js
  server/package.json
Labels: feature

#62 fix: backend bugs
  server/api/controllers/goal.js
  server/api/models/goal.js
  server/api/routes/goal.js
Labels: fix

#71 feat: feed
  server/api/controllers/feed.js
  server/api/controllers/goal.js
  server/api/models/feed.js
  server/api/routes/feed.js
  server/index.js
Labels: feature

#72 docs: update
  README.md
  server/README.md
Labels: documentation

#73 test: add rendering test for all components
  client/src/App.test.js
  client/src/components/__tests__/AddGoal.test.js
  client/src/components/__tests__/Comment.test.js
  client/src/components/__tests__/Feed.test.js
  client/src/components/__tests__/Goal.test.js
  client/src/components/__tests__/Nav.test.js
  client/src/components/__tests__/Slidebar.test.js
  client/src/setupTests.js
  client/src/views/__tests__/Activity.test.js
  client/src/views/__tests__/Leaderboard.test.js
  client/src/views/__tests__/Login.test.js
  client/src/views/__tests__/Onboarding.test.js
  client/src/views/__tests__/Signup.test.js
  client/src/views/__tests__/Today.test.js
Labels: testing

#70 Feat/shares
  client/src/App.jsx
  client/src/components/Details.jsx
  client/src/components/Nav.jsx
  client/src/components/OngoingGoal.jsx
  client/src/components/SharedGoal.jsx
  client/src/components/Sidebar.jsx
  client/src/views/Shares.jsx
  server/yarn.lock
Labels: feature

#78 Feat/feed
  server/api/controllers/goal.js
  server/api/controllers/user.js
  server/api/routes/user.js
Labels: feature, fix

#79 feat: leaderboard view
  client/src/App.jsx
  client/src/components/AddGoal.jsx
  client/src/components/NavItem.jsx
  client/src/components/Rank.jsx
  client/src/components/Sidebar.jsx
  client/src/components/TopRank.jsx
  client/src/views/Goals.jsx
  client/src/views/Leaderboard.jsx
  client/src/views/Shares.jsx
  client/src/views/Today.jsx
  server/api/controllers/user.js
  server/yarn.lock
Labels: feature

#76 feat: Profile view and activity view
  client/src/App.jsx
  client/src/assets/Feed_climbing.png
  client/src/assets/ImageLarge.png
  client/src/components/CompletedProfile.jsx
  client/src/components/Details.jsx
  client/src/components/Feed.jsx
  client/src/components/GoalFromProfile.jsx
  client/src/components/Nav.jsx
  client/src/components/Sidebar.jsx
  client/src/views/Activity.jsx
  client/src/views/Profile.jsx
  server/api/controllers/feed.js
  server/api/controllers/user.js
  server/api/routes/feed.js
  server/api/routes/user.js
Labels: feature

#80 refactor: state loading fix
  client/package.json
  client/src/App.jsx
  client/src/components/AddGoal.jsx
  client/src/components/CheckInModal.jsx
  client/src/components/Details.jsx
  client/src/components/Feed.jsx
  client/src/components/Goal.jsx
  client/src/components/Loader.jsx
  client/src/components/Nav.jsx
  client/src/components/OngoingGoal.jsx
  client/src/components/SharedGoal.jsx
  client/src/components/Sidebar.jsx
  client/src/views/Activity.jsx
  client/src/views/Goals.jsx
  client/src/views/Leaderboard.jsx
  client/src/views/Login.jsx
  client/src/views/Profile.jsx
  client/src/views/Shares.jsx
  client/src/views/Signup.jsx
  client/src/views/Today.jsx
  client/yarn.lock
  server/api/controllers/feed.js
  server/api/controllers/goal.js
  server/api/middleware/auth.js
Labels: feature, fix, refactor

#82 fix: apply loading on login
  client/src/App.jsx
  client/src/views/Login.jsx
Labels: fix

#81 Feat/admin
  server/api/controllers/feed.js
  server/api/controllers/goal.js
  server/api/controllers/user.js
  server/api/middleware/admin.js
  server/api/models/goal.js
  server/api/models/user.js
  server/api/routes/goal.js
  server/api/routes/user.js
Labels: feature, fix

#91 feat: feed, comment system
  client/src/App.jsx
  client/src/components/Comment.jsx
  client/src/components/Feed.jsx
  client/src/components/Sidebar.jsx
  client/src/views/Activity.jsx
  client/src/views/SingleFeed.jsx
  server/api/controllers/feed.js
  server/api/models/feed.js
  server/api/routes/feed.js
  server/package.json
  server/yarn.lock
Labels: feature, fix, refactor

#92 fix: today tasks left
  client/src/views/Today.jsx
  server/api/controllers/goal.js
Labels: fix

#94 Fix & Feat: debug some front-end style and created verification views
  client/src/App.jsx
  client/src/assets/verification.png
  client/src/components/Details.jsx
  client/src/components/Goal.jsx
  client/src/views/Activity.jsx
  client/src/views/Leaderboard.jsx
  client/src/views/Login.jsx
  client/src/views/Profile.jsx
  client/src/views/Shares.jsx
  client/src/views/Signup.jsx
  client/src/views/Verification.jsx
Labels: feature, fix

#95 feat: retrieve propic for users
  client/src/App.jsx
  client/src/assets/image.jpg
  client/src/components/Comment.jsx
  client/src/components/Feed.jsx
  client/src/components/Nav.jsx
  client/src/components/Rank.jsx
  client/src/components/SharedGoal.jsx
  client/src/components/Sidebar.jsx
  client/src/components/TopRank.jsx
  client/src/contexts/AuthContext.jsx
  client/src/views/Profile.jsx
  client/src/views/SingleFeed.jsx
  server/api/controllers/goal.js
  server/api/controllers/user.js
  server/api/models/goal.js
  server/api/routes/user.js
Labels: feature

#97 feat: admin frontend
  .gitignore
  client/src/App.jsx
  client/src/components/SharedGoal.jsx
  client/src/components/Sidebar.jsx
  client/src/components/User.jsx
  client/src/views/Shares.jsx
  client/src/views/Users.jsx
  server/api/controllers/feed.js
  server/api/controllers/goal.js
  server/api/controllers/user.js
  server/api/middleware/admin.js
  server/api/models/feed.js
  server/api/routes/user.js
Labels: feature, fix

#98 fix: nav hover bugs
  client/src/components/Sidebar.jsx
Labels: fix

#106 fix: signup
  client/src/views/Signup.jsx
Labels: fix

#107 fix: accuracy
  server/api/controllers/goal.js
Labels: fix

#108 fix: hot fixs and style
  client/public/index.html
  client/src/assets/Onboarding_3.png
  client/src/components/AddGoal.jsx
  client/src/components/Comment.jsx
  client/src/components/SharedGoal.jsx
  client/src/views/Onboarding.jsx
  client/src/views/OtherProfile.jsx
  client/src/views/Profile.jsx
  client/src/views/Signup.jsx
Labels: feature, fix, refactor, style

#109 fix: minor fix styling
  client/src/App.jsx
  client/src/components/AddGoal.jsx
  client/src/components/TopRank.jsx
  client/src/views/Leaderboard.jsx
  client/src/views/Onboarding.jsx
  client/src/views/Today.jsx
Labels: fix, style

#110 fix: broken codes
  client/src/components/CompletedProfile.jsx
  client/src/components/Details.jsx
  client/src/components/OtherUserGoal.jsx
  client/src/components/Rank.jsx
  client/src/components/TopRank.jsx
  client/src/views/OtherProfile.jsx
  client/src/views/Profile.jsx
Labels: fix, style

#111 style: select box
  client/src/views/Leaderboard.jsx
Labels: fix

#118 test: backend testing
  server/README.md
  server/__tests__/goal.test.js
  server/__tests__/user.test.js
  server/api/controllers/feed.js
  server/api/controllers/user.js
  server/index.js
  server/package.json
  server/yarn.lock
Labels: testing

#119 test: more test data
  server/__tests__/user.test.js
Labels: testing

#115 Test/frontend testing
  client/src/App.jsx
  client/src/App.test.js
  client/src/components/Nav.jsx
  client/src/components/NavItem.jsx
  client/src/components/OngoingGoal.jsx
  client/src/components/Rank.jsx
  client/src/components/Sidebar.jsx
  client/src/components/TopRank.jsx
  client/src/components/User.jsx
  client/src/components/__tests__/AddGoal.test.js
  client/src/components/__tests__/CheckInModal.test.js
  client/src/components/__tests__/Comment.test.js
  client/src/components/__tests__/Feed.test.js
  client/src/components/__tests__/GoalFromProfile.test.js
  client/src/components/__tests__/Loader.test.js
  client/src/components/__tests__/Nav.test.js
  client/src/components/__tests__/NavItem.test.js
  client/src/components/__tests__/OngoingGoal.test.js
  client/src/components/__tests__/OtherUserGoal.test.js
  client/src/components/__tests__/Overlay.test.js
  client/src/components/__tests__/Rank.test.js
  client/src/components/__tests__/TopRank.test.js
  client/src/components/__tests__/User.test.js
  client/src/setupTests.js
  client/src/views/Goals.jsx
  client/src/views/__tests__/Activity.test.js
  client/src/views/__tests__/Leaderboard.test.js
  client/src/views/__tests__/Login.test.js
  client/src/views/__tests__/Onboarding.test.js
  client/src/views/__tests__/Signup.test.js
  client/src/views/__tests__/Today.test.js
Labels: testing
