Repository IamMrandrew/aimimi, pull requests merged in 2021-03, with the labels that each got.

#15 feat/today page
  client/public/index.html
  client/src/App.js
  client/src/App.jsx
  client/src/assets/ProfilePhoto.png
  client/src/components/GlobalStyle.jsx
  client/src/components/Goal.jsx
  client/src/components/Nav.jsx
  client/src/components/Sidebar.jsx
  client/src/components/Today.jsx
  client/src/index.jsx
Labels: feature

#16 Build/server
  .gitignore
  server/index.js
  server/package.json
Labels: build

#17 build: yarn.lock
  server/yarn.lock
Labels: build

#18 feat: login page
  client/package.json
  client/src/App.jsx
  client/src/assets/LogInBack.png
  client/src/components/GlobalStyle.jsx
  client/src/views/Login.jsx
  client/src/views/Signup.jsx
  client/src/views/Today.jsx
  client/yarn.lock
Labels: feature

#20 feat: styling goal component
  client/src/App.jsx
  client/src/components/GlobalStyle.jsx
  client/src/components/Goal.jsx
  client/src/components/Nav.jsx
  client/src/views/Today.jsx
Labels: style

#24 style: ui update
  client/src/assets/Logo.svg
  client/src/components/GlobalStyle.jsx
  client/src/components/Goal.jsx
  client/src/components/Nav.jsx
  client/src/components/Sidebar.jsx
  client/src/views/Login.jsx
  client/src/views/Signup.jsx
  client/src/views/Today.jsx
Labels: style

#26 docs: readme
  README.md
Labels: documentation

#25 build: deploy heroku
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  package.json
  server/api/routes/goal.js
  server/api/routes/user.js
  server/index.js
  server/package.json
  server/yarn.lock
  yarn.lock
Labels: build

#27 docs: update .env setting
  README.md
Labels: documentation

#28 build: add cors
  server/package.json
  server/yarn.lock
Labels: build, fix

#29 feat: add goal
  client/package.json
  client/src/App.jsx
  client/src/components/AddGoal.jsx
  client/src/components/GlobalStyle.jsx
  client/src/views/Login.jsx
  client/src/views/Today.jsx
  server/api/controllers/user.js
Labels: feature

#32 feat: http only cookies
  client/package.json
  client/src/App.jsx
  client/src/components/AddGoal.jsx
  client/src/views/Login.jsx
  client/src/views/Today.jsx
  client/yarn.lock
  server/api/controllers/user.js
  server/api/middleware/auth.js
  server/api/routes/user.js
  server/index.js
  server/package.json
  server/yarn.lock
Labels: feature

#31 feat: onboarding page
  client/src/App.jsx
  client/src/assets/Logo.svg
  client/src/assets/Onboarding_1.png
  client/src/assets/Onboarding_2.png
  client/src/components/Sidebar.jsx
  client/src/views/Onboarding.jsx
Labels: feature

#34 feat: auth user, signup, logout, login
  client/src/App.jsx
  client/src/components/Nav.jsx
  client/src/components/Sidebar.jsx
  client/src/views/Login.jsx
  client/src/views/Signup.jsx
  server/api/controllers/user.js
  server/api/routes/user.js
  server/index.js
Labels: feature

#35 docs: update docs
  README.md
Labels: documentation

#36 feat: refine add goal
  client/src/App.jsx
  client/src/components/AddGoal.jsx
  client/src/components/Goal.jsx
Labels: style

#38 refactor: initialize views and components
  client/src/components/Comment.jsx
  client/src/components/Feed.jsx
  client/src/views/Activity.jsx
  client/src/views/Leaderboard.jsx
Labels: refactor

#37 feat: fetch on boarding
  client/src/App.jsx
  client/src/components/Nav.jsx
  client/src/index.jsx
  client/src/views/Login.jsx
Labels: feature
